// import { AuthContextProvider } from "@/contexts/auth-context";

export const metadata = {
  title: "我的網站",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
        </head>
        <body>
          {children}
          {/* <script
            defer
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          ></script> */}
        </body>
      </html>
    </>
  );
}
