import Script from "next/script";
import '@/styles/globals.css'
import Providers from './providers'
import { AuthContextProvider } from "@/context/auth-context";
import dynamic from "next/dynamic";

const AiChatWidget = dynamic(() => import("@/components/AiChatWidget"), {
  ssr: false,
});

export const metadata = {
  title: "TeamB的網站",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          {/* 引入google字體 */}
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
            rel="stylesheet"
          />
          {/* 引入 Bootstrap CSS */}
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
          />
        </head>
        <body>
        <AuthContextProvider>
          <Providers>
            <AiChatWidget />
            {children}
          </Providers>
        </AuthContextProvider>  
        

          {/* 引入 Bootstrap JS */}
          <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></Script>

          {/* 引入 MotionPathPlugin */}
          <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/MotionPathPlugin.min.js"></Script>

          {/* 引入 GSAP 動畫 */}
          <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></Script>
        </body>
      </html>
    </>
  );
}
